### PR TITLE
Static design

### PR DESCRIPTION
**Pull request by AhmedEssamMo**

### CODE REVIEW

**Comment by MohSamyN** [comment]
I think Motor driver needs an API to specify the speed and the direction of the motor.
Otherwise, the whole design is perfect.

**Review by MohSamyN — APPROVED** [review]
I think Motor driver needs an API to specify the speed and the direction of the motor.
Otherwise, the whole design is perfect.

**Comment by AhmedEssamMo** [comment]
Dear Mohamed,

Thank you for your feedback.
Yes, I think I missed that, I will add those APIs and get back to you soon.

Best regards,
Ahmed Essam

________________________________

**Comment by AhmedEssamMo** [comment]
Thank you Moahmed for your feedback.
Yes, I think I missed that, I will add those APIs and get back to you soon.
________________________________

**Pull request closed without merging**
